# Generated by Django 2.0.6 on 2018-06-22 00:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='', max_length=200)),
                ('picture_url', models.URLField(default='', max_length=500)),
                ('status_message', models.CharField(default='', max_length=500)),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'LINE Account',
                'verbose_name_plural': 'LINE Accounts',
            },
        ),
    ]
