# Generated by Django 2.0.6 on 2018-06-21 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Line',
            fields=[
                ('user_id', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('display_name', models.CharField(default='', max_length=200)),
                ('picture_url', models.URLField(default='', max_length=500)),
                ('status_message', models.CharField(default='', max_length=500)),
            ],
            options={
                'verbose_name': 'LINE Account',
                'verbose_name_plural': 'LINE Accounts',
            },
        ),
    ]
